---
title: "Nouveu modele lineaire"
output: html_document
date: "2024-12-13"
---


## Présentation du jeu de données et enlèvement des données inutiles

Nous étudierons un jeu de données provenant de Kaggle. C'est un document CSV qui recense 109 observations de données (mois, année, pluviométrie, température, humidité), à Berlin entre 2015 et 2023.

```{r echo=FALSE}
```


```{r echo=FALSE}
df <- read.table(file = "Rainfall_Data_Germany_Complete.csv", header = T, sep=",", fill = T, fileEncoding = "Latin1")
```


```{r echo=FALSE}
for (i in 1:12) {
  mois_col_name <- month.name[i]  # Noms complets des mois (Janvier, Février, etc.)
  df[[mois_col_name]] <- ifelse(df$Month == i, 1, 0)
}

for (year in 2015:2023) {
  year_col_name <- as.character(year)  # Nom de la colonne (par exemple "2015", "2016", etc.)
  df[[year_col_name]] <- ifelse(df$Year == year, 1, 0)
}

data = df[,!(names(df) %in% c("City", "Year", "Month", "Latitude", "Longitude", "Elevation..m.", "Climate_Type"))] #On enleve les données inutiles
data
```

## Estimation des paramètres


```{r}
df$January <- as.factor(df$January)
df$February <- as.factor(df$February)
df$March <- as.factor(df$March)
df$April <- as.factor(df$April)
df$May <- as.factor(df$May)
df$June <- as.factor(df$June)
df$July <- as.factor(df$July)
df$August <- as.factor(df$August)
df$September <- as.factor(df$September)
df$October <- as.factor(df$October)
df$November <- as.factor(df$November)
df$December <- as.factor(df$December)

mod1 <- lm(Rainfall..mm. ~ ., data = data)
mod1
```

```{r}
df <- read.table(file = "Rainfall_Data_Germany_Complete.csv", header = T, sep=",", fill = T, fileEncoding = "Latin1")
df
data = df[,!(names(df) %in% c("City", "Year", "Month", "Latitude", "Longitude", "Elevation..m.", "Climate_Type"))]
data
```

